dag:
- access_control: null
  auto_register: false
  catchup: false
  concurrency: null
  created_at: 2024-07-26 13:11:39.808021+00:00
  dag_id: ScrapingDepartment
  dagrun_timeout: null
  default_args: null
  default_view: ''
  deleted_at: null
  description: purpose of this department is to assign leads to their appropriate
    sales reps or influencers
  doc_md: ''
  end_date: null
  fail_stop: false
  full_filepath: ''
  id: -O2j9m-gJw4wB0hETp4F
  is_paused_upon_creation: false
  jinja_environment_kwargs: null
  max_active_runs: null
  max_active_tasks: null
  on_failure_callback: ''
  on_success_callback: ''
  orientation: ''
  owner_links: null
  params: null
  render_template_as_native_obj: false
  schedule: '@daily'
  schedule_interval: 17 8-21/2 * * *
  sla_miss_callback: ''
  start_date: null
  tags: []
  template_searchpath: ''
  template_undefined: ''
  timetable: ''
  trigger_url: https://httpbin.org/get
  trigger_url_expected_response: https://httpbin.org/get
  updated_at: 2024-07-26 13:11:39.808065+00:00
  user_defined_filters: null
  user_defined_macros: null
data_seconds:
  '2': 720.0
operators:
- created_at: 2024-07-26 13:11:33.878755+00:00
  data:
    chain: true
    index: 0
    round: 1908
  deleted_at: null
  endpoint: instagram/scrapingPayload/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -O2j9kZKoCyU_j-QZmiT
  log_response: true
  method: POST
  response_check: ''
  task_id: initializeLead
  updated_at: 2024-07-26 13:11:33.878774+00:00
  urls: null
  xcom_push: false
- created_at: 2024-07-26 13:11:35.830846+00:00
  data: null
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -O2j9l1hiv0sDDSINRPv
  log_response: true
  method: POST
  response_check: ''
  task_id: kicstart_Scrapping_Agents
  updated_at: 2024-07-26 13:11:35.830869+00:00
  urls:
  - '{"set_of_urls": [{"url": "https://promptemplate.booksy.us.boostedchat.com/agentSetup/",
    "delay": 105}], "attempt": 1, "delay": 24}'
  xcom_push: true
- created_at: 2024-07-26 13:11:37.804521+00:00
  data:
    accounts: 18
    chain: false
    delay_after_requests: 14
    delay_before_requests: 4
    index: 0
    round: 121
    step: 3
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -O2j9lWht7nmDBZ9mMEs
  log_response: true
  method: POST
  response_check: ''
  task_id: enrichScrappedUserprofilesWithInstagramInfo
  updated_at: 2024-07-26 13:11:37.804593+00:00
  urls: null
  xcom_push: false
trigger_url: https://httpbin.org/get
trigger_url_expected_response: https://httpbin.org/get
