dag:
- access_control: null
  auto_register: false
  catchup: false
  concurrency: null
  created_at: 2024-04-16 12:14:34.340799+00:00
  dag_id: scrapUsersInfoInsertEnrichFromStyleseat
  dagrun_timeout: null
  default_args: null
  default_view: ''
  deleted_at: null
  description: adf
  doc_md: ''
  end_date: null
  fail_stop: false
  full_filepath: ''
  id: 123fasdxasdfacmaasdfdfaasmajoofasdfdfop213oasdpf
  is_paused_upon_creation: false
  jinja_environment_kwargs: null
  max_active_runs: null
  max_active_tasks: null
  on_failure_callback: ''
  on_success_callback: ''
  orientation: ''
  owner_links: null
  params: null
  render_template_as_native_obj: false
  schedule: '@daily'
  schedule_interval: 10 8 5 4 *
  sla_miss_callback: ''
  start_date: null
  tags: []
  template_searchpath: ''
  template_undefined: ''
  timetable: ''
  updated_at: 2024-04-16 12:14:34.340833+00:00
  user_defined_filters: null
  user_defined_macros: null
data_seconds:
  '2': 720.0
operators:
- created_at: 2024-04-16 12:14:22.140559+00:00
  data:
    category: natural-hair
    chain: true
    index: 0
    region: wilmington
    round: 13
  deleted_at: null
  endpoint: instagram/scrapStyleseat/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NgcH1oobGricGaaas78af23akljasdfdfgwrmajooffsdfOLs1adf235adf
  log_response: true
  method: POST
  response_check: ''
  task_id: getUsers
  updated_at: 2024-04-16 12:14:22.140602+00:00
  xcom_push: false
- created_at: 2024-04-16 12:14:25.502484+00:00
  data:
    accounts: 18
    chain: true
    delay_after_requests: 14
    delay_before_requests: 4
    index: 0
    round: 13
    step: 3
  deleted_at: null
  endpoint: instagram/scrapInfo/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NgcH1oobx78vddfd1ipoasdf23fOasdfmajoofLasfs5
  log_response: true
  method: POST
  response_check: ''
  task_id: getInfo
  updated_at: 2024-04-16 12:14:25.502522+00:00
  xcom_push: false
- created_at: 2024-04-16 12:14:28.469585+00:00
  data:
    chain: true
    keywords_to_check:
    - hair
    - appointment
    - appointments
    - book
    - call
    - book.thecut.co
    - licensed
    - cutz
    - kutz
    - cuts
    - cut
    - hairstylist
    - salon
    - salons
    - educator
    - specialist
    - beauty
    - barber
    - walk
    - text
    - stylist
    - colour
    - colouring
    - loreal
    - olaplex
    - hairspray
    - mousse
    - pomade
    - hair oil
    - hair serum
    - scissors
    - comb
    - brush
    - blow dryer
    - flat iron
    - curling iron
    - hair rollers
    - hair clips
    - hair ties
    - headbands
    - hair accessories
    - updos
    - braids
    - twists
    - buns
    - ponytails
    - curls
    - waves
    - volume
    - texture
    - shine
    - frizz control
    - breakage
    - dryness
    - oiliness
    - thinning
    - hair loss
    - dandruff
    - scalp problems
    round: 13
  deleted_at: null
  endpoint: instagram/insertAndEnrich/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: your_http_connection
  id: -NgcH1oobGrO78Laodf235zxs213sdfaamajoofsfdfgcvfs5
  log_response: true
  method: POST
  response_check: ''
  task_id: enrich
  updated_at: 2024-04-16 12:14:28.469599+00:00
  xcom_push: false
- created_at: 2024-04-16 12:14:31.470889+00:00
  data:
    num_tasks: ''
    start_hour: 3
    start_minute: 30
    tasks_per_day: 24
  deleted_at: null
  endpoint: /v1/outreaches/tasks/reschedule_all/
  extra_options: null
  headers:
    Content-Type: application/json
  http_conn_id: api_conn
  id: -NgcH1oobiGUGO78Llkald2asfs123werfdfgasmajoofdf35zxcv
  log_response: true
  method: POST
  response_check: ''
  task_id: reschedule
  updated_at: 2024-04-16 12:14:31.470926+00:00
  xcom_push: false
